services:
  vote:
    image: /app
    container_name: vote
    ports: #Port mapping: 5000 is used inside the container (see Python code). Each instance of vote will use the external port 500x where x is the instance number
      - "5000:5000"
      - "5000:5001"
    networks:
      - front-tier
      - back-tier

  result:
    networks:
      - front-tier
      - back-tier

  seed:
    networks:
      - front-tier

  worker:
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier: {}
  back-tier: {}

