upstream loadbalancer {
    # Machines onto which nginx should balance the incomming load of requests
    server 0.0.0.0:5000;
    server 0.0.0.0:5001;
}
server {
    # Server configuration
    listen 0.0.0.0:80;
    location / {
    proxy_pass http://loadbalancer;
}}
